# MySQL
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: refsort_dev

test:
  <<: *default
  database: refsort_test

production:
  <<: *default
  database: refsort_prd
